########################################################################
# GAHM CircleCI Yaml
#
# Written By: Zach Cobell
#
# Generated for: CircleCI v2.0
#
########################################################################
version: 2.1
jobs:
  build:
      docker:
        - image: zcobell/adcirc_20200513 
      steps:
        - checkout
        - run: 
            name: Build GAHM 
            command: mkdir build; cd build; cmake .. -DGAHM_ENABLE_TESTING=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-O3 -DNDEBUG -march=native -fprofile-arcs -ftest-coverage -g -funroll-loops --param max-unroll-times=4"; make -j
        - run: 
            name: Test GAHM
            command: cd build; make test
        - run: 
            name: Generate coverage report
            command: coveralls --exclude thirdparty --exclude testing --exclude build/CMakeFiles/3.5.1 --gcov-options '\-lp'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
