########################################################################
# GAHM CircleCI Yaml
#
# Written By: Zach Cobell
#
# Generated for: CircleCI v2.0
#
########################################################################
version: 2
jobs:
  build:
      docker:
        - image: zcobell/adcirc_20200513 
      steps:
        - checkout
        - run: 
            name: Build GAHM 
            command: mkdir build; cd build; cmake .. -DGAHM_ENABLE_TESTING=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-O3 -DNDEBUG -march=native -fprofile-arcs -ftest-coverage -g -funroll-loops --param max-unroll-times=4"; make -j
        - run: 
            name: Test GAHM
            command: cd build; make test
        - run: 
            name: Cleaning reports
            command: rm $(find . -name "*.gcov" | grep thirdparty\|testing)
        - run: 
            name: Generate coverage report
            command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
