name: Testing
on:
  push:
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt install -y clang-15 llvm-15 libfuzzer-15-dev libnetcdf-dev cmake libboost-all-dev libssl-dev swig libpython3-dev gfortran
      - name: Make directories
        run: mkdir build
      - name: CMake
        run: cmake .. -DGAHM_ENABLE_TESTS=ON -DGAHM_ENABLE_FUZZ=ON -DCMAKE_CXX_COMPILER=clang++ -DENABLE_SANITIZER_ADDRESS=ON -DENABLE_SANITIZER_LEAK=ON -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON -DGAHM_ENABLE_FORTRAN=ON -DGAHM_ENABLE_PYTHON=ON
        working-directory: ./build
      - name: Build
        run: make -j
        working-directory: ./build
      - name: Run Tests
        run: ctest --output-on-failure
        working-directory: ./build
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt install -y gfortran libnetcdf-dev cmake libboost-all-dev libssl-dev
      - name: Make directories
        run: mkdir build
      - name: CMake
        run: cmake .. -DGAHM_ENABLE_TESTS=ON -DGAHM_ENABLE_FORTRAN=ON -DGAHM_ENABLE_COVERAGE=ON
        working-directory: ./build
      - name: Build
        run: make -j
        working-directory: ./build
      - name: Run Tests
        run: ctest --output-on-failure
        working-directory: ./build
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          verbose: true
          gcov: true
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt install -y libnetcdf-dev cmake libboost-all-dev libssl-dev
      - name: Make directories
        run: mkdir build
      - name: CMake
        run: cmake .. -DCMAKE_CXX_COMPILER=clang++ -DGAHM_ENABLE_TESTS=ON -DGAHM_ENABLE_BENCHMARKS=ON; cmake ..
        working-directory: ./build
      - name: Build
        run: make -j
        working-directory: ./build
      - name: Run Benchmark
        run: ./tests/benchmark/gahm_benchmark --benchmark_out_format=json --benchmark_out=benchmark.json
        working-directory: ./build
      - name: Store Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: GAHM Benchmark
          tool: 'googlecpp'
          output-file-path: './build/benchmark.json'
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@zcobell'
          github-token: ${{ secrets.GITHUB_TOKEN }}
